version: "3"

tasks:

  run:
    cmd: v -cc clang run main.v

  build:
    cmds:
      - mkdir -p build
      - v -cc clang -o build/yamc .
  
  setup:
    cmds:
      - task: init-submodules
      - task: build-wgpu
  
  init-submodules:
    cmd: git submodule update --init --recursive
  
  update-submodules:
    cmd: git submodule update --recursive

  build-wgpu:
    cmds:
      - make -C submodules/wgpu-native lib-native
      - cp submodules/wgpu-native/target/debug/libwgpu_native.a libraries
